#!/usr/bin/env bash
# Hunter PII Scanner — scan hunter machine for owner's personal information residue
#
# Usage:
#   SSH into hunter, then run:
#     bash scripts/security/scan_hunter_pii.sh
#   Or from captain:
#     ssh hunter 'cd ~/FAS-operations && bash scripts/security/scan_hunter_pii.sh'
#
# What it checks:
#   1. Claude Code auth state (계정 A vs B)
#   2. Browser profiles for owner's Google account cookies
#   3. Shell history for PII patterns
#   4. .env files for captain secrets
#   5. Git config for owner email
#   6. SSH keys / known_hosts for identifying info
#   7. File content scan across common directories
#
# This script is READ-ONLY — it only reports findings, never deletes anything.
# After review, use scan_hunter_pii.sh --clean to generate cleanup commands.

set -euo pipefail

MODE="${1:-scan}"  # scan (default) or clean
REPORT_FILE="./logs/pii_scan_$(date +%Y%m%d_%H%M%S).md"
FOUND_COUNT=0

# === Colors ===
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

# === PII patterns (from .notebooklm-mask + sanitizer.ts) ===
# Owner-specific patterns — loaded from .notebooklm-mask if available
OWNER_PATTERNS=()
MASK_FILE=".notebooklm-mask"

# Also check project root and script directory for mask file
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

for candidate in "$MASK_FILE" "$PROJECT_ROOT/.notebooklm-mask"; do
  if [ -f "$candidate" ]; then
    while IFS='|' read -r pattern _replacement; do
      [[ "$pattern" =~ ^#.*$ ]] && continue
      [[ -z "$pattern" ]] && continue
      OWNER_PATTERNS+=("$pattern")
    done < "$candidate"
    break
  fi
done

# If no mask file found (e.g., on hunter where it's intentionally absent),
# skip owner-pattern checks gracefully instead of failing
if [ ${#OWNER_PATTERNS[@]} -eq 0 ]; then
  echo -e "${YELLOW}[INFO]${NC} No .notebooklm-mask found — skipping owner-specific PII patterns (generic patterns still active)"
fi

# Generic PII regex patterns (from sanitizer.ts)
GENERIC_PATTERNS=(
  '01[016789][- ]?[0-9]{3,4}[- ]?[0-9]{4}'          # Korean phone numbers
  '[0-9]{6}-?[1-4][0-9]{6}'                            # Resident ID
  '[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'   # Email (generic)
)

mkdir -p "$(dirname "$REPORT_FILE")"

# === Helper functions ===
log_finding() {
  local severity="$1"  # CRITICAL / WARNING / INFO
  local category="$2"
  local detail="$3"

  FOUND_COUNT=$((FOUND_COUNT + 1))

  case "$severity" in
    CRITICAL) echo -e "${RED}[CRITICAL]${NC} $category: $detail" ;;
    WARNING)  echo -e "${YELLOW}[WARNING]${NC} $category: $detail" ;;
    INFO)     echo -e "${GREEN}[INFO]${NC} $category: $detail" ;;
  esac

  echo "- [$severity] **$category**: $detail" >> "$REPORT_FILE"
}

log_clean() {
  echo -e "${GREEN}[CLEAN]${NC} $1"
}

# === Start ===
echo "=== FAS Hunter PII Scanner ==="
echo "Mode: $MODE"
echo "Report: $REPORT_FILE"
echo ""

cat > "$REPORT_FILE" << 'HEADER'
# Hunter PII Scan Report

> Auto-generated by scripts/security/scan_hunter_pii.sh

## Findings

HEADER

# ===== 1. Claude Code Auth State =====
echo "--- [1/7] Claude Code auth state ---"

if command -v claude &>/dev/null; then
  CLAUDE_WHO=$(claude whoami 2>/dev/null || echo "NOT_LOGGED_IN")
  if echo "$CLAUDE_WHO" | grep -qi "not_logged_in\|error\|not authenticated"; then
    log_clean "Claude Code: not logged in"
  else
    # Check if it looks like owner's account (Account A)
    log_finding "CRITICAL" "Claude Code Auth" "Logged in as: $CLAUDE_WHO — verify this is Account B, not Account A"
  fi
else
  log_clean "Claude Code: not installed"
fi

# Check for credential files
for cred_file in ~/.claude/.credentials.json ~/.claude/credentials.json ~/.claude/auth.json ~/.claude/oauth*; do
  if [ -f "$cred_file" ]; then
    log_finding "WARNING" "Claude Credentials" "Found credential file: $cred_file"
  fi
done
echo ""

# ===== 2. Browser Profiles =====
echo "--- [2/7] Browser profiles ---"

# Check Chrome/Chromium profiles for Google account cookies
BROWSER_DIRS=(
  "$HOME/Library/Application Support/Google/Chrome"
  "$HOME/Library/Application Support/Chromium"
  "$HOME/.config/google-chrome"
  "$HOME/.config/chromium"
  "$HOME/fas-google-profile-hunter"
  "${GOOGLE_PROFILE_DIR:-./fas-google-profile-hunter}"
)

for dir in "${BROWSER_DIRS[@]}"; do
  if [ -d "$dir" ]; then
    # Check for Google account info in Preferences files
    prefs=$(find "$dir" -name "Preferences" -maxdepth 3 2>/dev/null || true)
    for pref in $prefs; do
      if [ -f "$pref" ] && [ ${#OWNER_PATTERNS[@]} -gt 0 ]; then
        # Look for owner email patterns
        for pattern in "${OWNER_PATTERNS[@]}"; do
          if grep -qi "$pattern" "$pref" 2>/dev/null; then
            log_finding "CRITICAL" "Browser Profile" "Owner pattern '$pattern' found in $pref"
          fi
        done
      fi
    done

    # Check Login Data sqlite for owner's accounts
    login_dbs=$(find "$dir" -name "Login Data" -maxdepth 3 2>/dev/null || true)
    if [ -n "$login_dbs" ]; then
      log_finding "INFO" "Browser Profile" "Login database found in $dir — may contain saved passwords"
    fi
  fi
done
echo ""

# ===== 3. Shell History =====
echo "--- [3/7] Shell history ---"

HISTORY_FILES=(
  "$HOME/.bash_history"
  "$HOME/.zsh_history"
  "$HOME/.history"
)

for hist in "${HISTORY_FILES[@]}"; do
  if [ -f "$hist" ]; then
    if [ ${#OWNER_PATTERNS[@]} -gt 0 ]; then
      for pattern in "${OWNER_PATTERNS[@]}"; do
        matches=$(grep -ci "$pattern" "$hist" 2>/dev/null || echo "0")
        if [ "$matches" -gt 0 ]; then
          log_finding "WARNING" "Shell History" "'$pattern' appears $matches times in $hist"
        fi
      done
    fi

    # Check for generic PII
    for pattern in "${GENERIC_PATTERNS[@]}"; do
      matches=$(grep -cE "$pattern" "$hist" 2>/dev/null | tr -d '[:space:]' || echo "0")
      if [ "$matches" -gt 0 ]; then
        log_finding "WARNING" "Shell History" "PII pattern match ($matches) in $hist"
      fi
    done
  fi
done
echo ""

# ===== 4. Environment / Config Files =====
echo "--- [4/7] Environment & config files ---"

# Check .env files for captain secrets
ENV_FILES=(
  "$HOME/FAS-operations/.env"
  "$HOME/FAS-operations/.env.local"
  "$HOME/.env"
)

for env_file in "${ENV_FILES[@]}"; do
  if [ -f "$env_file" ]; then
    # Check for captain-only secrets (should NOT be on hunter)
    for key in TELEGRAM_BOT_TOKEN SLACK_BOT_TOKEN NOTION_API_KEY GEMINI_API_KEY SMS_API_KEY; do
      val=$(grep "^${key}=" "$env_file" 2>/dev/null | cut -d= -f2 || true)
      if [ -n "$val" ] && [ "$val" != "" ] && [[ ! "$val" =~ ^your_ ]]; then
        log_finding "CRITICAL" "Environment" "Captain secret '$key' found in $env_file — should NOT be on hunter"
      fi
    done

    # Check for owner PII patterns
    if [ ${#OWNER_PATTERNS[@]} -gt 0 ]; then
      for pattern in "${OWNER_PATTERNS[@]}"; do
        if grep -qi "$pattern" "$env_file" 2>/dev/null; then
          log_finding "CRITICAL" "Environment" "Owner PII '$pattern' found in $env_file"
        fi
      done
    fi
  fi
done

# Check git config
GIT_EMAIL=$(git config --global user.email 2>/dev/null || echo "")
GIT_NAME=$(git config --global user.name 2>/dev/null || echo "")

if [ ${#OWNER_PATTERNS[@]} -gt 0 ]; then
  for pattern in "${OWNER_PATTERNS[@]}"; do
    if echo "$GIT_EMAIL $GIT_NAME" | grep -qi "$pattern" 2>/dev/null; then
      log_finding "WARNING" "Git Config" "Owner pattern '$pattern' in git config (email=$GIT_EMAIL, name=$GIT_NAME)"
    fi
  done
fi
echo ""

# ===== 5. SSH / Auth Files =====
echo "--- [5/7] SSH & auth files ---"

if [ -d "$HOME/.ssh" ]; then
  # Check known_hosts for captain hostnames
  if [ -f "$HOME/.ssh/known_hosts" ]; then
    log_finding "INFO" "SSH" "known_hosts exists — contains host fingerprints (generally safe)"
  fi

  # Check SSH config for owner info
  if [ -f "$HOME/.ssh/config" ] && [ ${#OWNER_PATTERNS[@]} -gt 0 ]; then
    for pattern in "${OWNER_PATTERNS[@]}"; do
      if grep -qi "$pattern" "$HOME/.ssh/config" 2>/dev/null; then
        log_finding "WARNING" "SSH Config" "Owner pattern '$pattern' in SSH config"
      fi
    done
  fi
fi

# Check macOS Keychain for FAS-related items
if command -v security &>/dev/null; then
  fas_keys=$(security dump-keychain 2>/dev/null | grep -ci "fas\|anthropic\|claude" | tr -d '[:space:]' || echo "0")
  if [ "$fas_keys" -gt 0 ]; then
    log_finding "WARNING" "Keychain" "$fas_keys FAS/Anthropic/Claude entries found in keychain"
  fi
fi
echo ""

# ===== 6. Doctrine / Source Code Leak =====
echo "--- [6/7] Doctrine & source code leak ---"

# Check if Doctrine files exist on hunter (they should NOT)
DOCTRINE_PATHS=(
  "$HOME/Library/Mobile Documents/com~apple~CloudDocs/claude-config"
  "$HOME/claude-config"
  "$HOME/FAS-doctrine"
)

for dpath in "${DOCTRINE_PATHS[@]}"; do
  if [ -d "$dpath" ]; then
    log_finding "CRITICAL" "Doctrine Leak" "Doctrine directory found on hunter: $dpath"
  fi
done

# Check if iCloud Drive is syncing
if [ -d "$HOME/Library/Mobile Documents/com~apple~CloudDocs" ]; then
  icloud_count=$(find "$HOME/Library/Mobile Documents/com~apple~CloudDocs" -maxdepth 1 -type d 2>/dev/null | wc -l || echo "0")
  if [ "$icloud_count" -gt 1 ]; then
    log_finding "CRITICAL" "iCloud" "iCloud Drive is syncing on hunter — owner data may be present"
  fi
fi
echo ""

# ===== 7. Broad File Content Scan =====
echo "--- [7/7] Broad file content scan (owner patterns) ---"

SCAN_DIRS=(
  "$HOME/FAS-operations"
  "$HOME/Documents"
  "$HOME/Desktop"
  "$HOME/Downloads"
)

for dir in "${SCAN_DIRS[@]}"; do
  if [ -d "$dir" ] && [ ${#OWNER_PATTERNS[@]} -gt 0 ]; then
    for pattern in "${OWNER_PATTERNS[@]}"; do
      matches=$(grep -rli "$pattern" "$dir" --include="*.{txt,md,json,yml,yaml,env,ts,js,sh,log}" 2>/dev/null | head -5 || true)
      if [ -n "$matches" ]; then
        file_count=$(echo "$matches" | wc -l | tr -d ' ')
        log_finding "WARNING" "File Content" "'$pattern' found in $file_count file(s) under $dir"
        echo "$matches" | while read -r f; do
          echo "    → $f"
          echo "  - \`$f\`" >> "$REPORT_FILE"
        done
      fi
    done
  fi
done
echo ""

# ===== Summary =====
echo "---" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "## Summary" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"
echo "- Total findings: $FOUND_COUNT" >> "$REPORT_FILE"
echo "- Scan time: $(date '+%Y-%m-%d %H:%M:%S')" >> "$REPORT_FILE"

echo "=== Scan Complete ==="
echo ""

if [ "$FOUND_COUNT" -eq 0 ]; then
  echo -e "${GREEN}✓ No PII found — hunter is clean.${NC}"
else
  echo -e "${YELLOW}Found $FOUND_COUNT issue(s). Review: $REPORT_FILE${NC}"
  echo ""
  echo "Recommended cleanup actions:"
  echo "  1. Claude Code: claude logout"
  echo "  2. Shell history: history -c && rm -f ~/.bash_history ~/.zsh_history"
  echo "  3. Browser profiles: rm -rf ~/fas-google-profile-hunter (then re-login with Account B)"
  echo "  4. Git config: git config --global user.email 'hunter@fas.local'"
  echo "  5. iCloud: Sign out of iCloud on this machine"
  echo "  6. Captain secrets in .env: Remove lines for TELEGRAM/SLACK/NOTION tokens"
  echo ""
  echo "After cleanup, re-run this script to verify."
fi

echo ""
echo "Full report: $REPORT_FILE"
